### ISSUE TITLE
Add partial evaluation

### ISSUE THREAD

**Issue by MarisaKirisame** [ThoughtWorksInc/DeepDarkFantasy#106]

**Comment by izgzhen** [comment]
http://okmij.org/ftp/tagless-final/course/PE-dB.html

**Comment by izgzhen** [comment]
I am trying out the PE-dB stuff now ... looks like I can simply copy over everything

**Comment by izgzhen** [comment]
https://gist.github.com/izgzhen/9e9555ecb08456c3007b7c935b96fad3

Not sure how to handle `liftEnv`...

**Comment by MarisaKirisame** [comment]
We dont have real HOAS, and HOAS is bad for PE.

**Comment by izgzhen** [comment]
> We dont have real HOAS

Yes, while being called `hoas`, it looks like de Brujin index for me.

**Comment by izgzhen** [comment]
Regarding `liftEnv`, can you explain a bit why it exists in the AST?

**Comment by MarisaKirisame** [comment]
It is De Brujin inside, but it is very painful to write DBI by hand, so we present a HOAS interface, which get translated to DBI.

**Comment by MarisaKirisame** [comment]
Hi, it is originally there since I though it is useful.
We dont really need it anywhere.

**Comment by izgzhen** [comment]
> We dont really need it anywhere.

Then I can't wait to drop it so my PE derivation might work somehow :)

**Comment by MarisaKirisame** [comment]
go ahead :)

**Comment by MarisaKirisame** [comment]
I am a bit busy, preparing for lambdaconf, so cant work on code this week. Sorry about that, but will look at them once I am done.
