### ISSUE TITLE
Macro in the object language?

### ISSUE THREAD

**Issue by MarisaKirisame** [ThoughtWorksInc/DeepDarkFantasy#129]
And it will be very, very dope if we can sorta do ad on them (in a meaningful way, whatever it mean)

**Comment by Atry** [comment]
Isn't Scala the macro language of your object language?

**Comment by MarisaKirisame** [comment]
@Atry scala macro = code gen, just like code gen for any other language(C/Go/C++/Whatever I couldnt care less)
I want something that generate code, but is written in DDF, not in scala

**Comment by Atry** [comment]
Isn't DDF a eDSL of Scala?

**Comment by MarisaKirisame** [comment]
Yes, but keep in mind that just because it is EDSL, doesnt mean object language/meta language distinction doesnt exist.
In general, a scala term is not a DDF term - it is DDF term only if it is in the form of LangTerm[X], for some X.
To be more straightforward, I want LangTerm[AST -> AST] or something similar, not LangTerm[X] => LangTerm[X].
