### ISSUE TITLE
https://people.csail.mit.edu/asolar/papers/pldi276-chaudhuri.pdf

### ISSUE THREAD

**Issue by MarisaKirisame** [ThoughtWorksInc/DeepDarkFantasy#169]

**Comment by rainoftime** [comment]
Smooth interpretation(

**Comment by rainoftime** [comment]
Related and Later work 

- Continuity analysis of programs. POPL 10
- Smoothing a program soundly and robustly. CAV 11
- Bridging Boolean and quantitative synthesis using smoothed proof search. POPL 14

**Comment by MarisaKirisame** [comment]
I am crawling the reference. All I found work only on imperative language without sum type (in one paper one even model program as transformation on bits, WTF)... Wonder if I am looking at the wrong place.

**Comment by rainoftime** [comment]
Yep. I guess it was not the thing you thought to be.

**Comment by MarisaKirisame** [comment]
http://mlg.eng.cam.ac.uk/pub/pdf/SciGhaGor15.pdf
Maybe we should do smooth interpretation by probabilistic sampling by embedding this into DDF...
