### ISSUE TITLE
category theory powered time travelling neural network

### ISSUE THREAD

**Issue by MarisaKirisame** [ThoughtWorksInc/DeepDarkFantasy#174]
Happy April Fool.
Do monad as a monoid under category of endofunctor.
Do Tardis.

**Comment by KiChjang** [comment]
Ever considered referencing [Cap'n Proto](https://capnproto.org/)? Their [time-travelling RPC](https://capnproto.org/rpc.html) contains a detailed design in how you might want to approach this.
