### ISSUE TITLE
abs function has a error

### ISSUE THREAD

**Issue by flyfish30** [ThoughtWorksInc/DeepDarkFantasy#179]
instance DBI Eval where
  z = Eval M.fst
  s (Eval a) = Eval $ a . M.snd
  abs (Eval f) = Eval $ \a h -> f (h, a)

Above definition of abs function is not error, but the better definition is show in bellow:
abs (Eval f) = Eval $ \h a -> f (a, h)

**Comment by dramforever** [comment]
I believe the current one is correct.

```hs
f :: (a, h) -> b
(\a h -> f (h, a))  :: h -> (a -> b)
```

Makes complete sense!

On the other hand, swapping `a` and `h` would give better variable names.

**Comment by flyfish30** [comment]
@dramforever 我并没有说原来的实现是错的呀，只是有更好的实现，而且我的修改和你的是一样的，为什么给我个down呢？

**Comment by dramforever** [comment]
@flyfish30 Sorry 当时我看错了

**Comment by dramforever** [comment]
@flyfish30 我明白了，有人在一个群里给我发了个邮件截图里面写的是

```hs
abs (Eval f) = Eval $ \a h -> f (a, h)
```

而你后来改了。是我没再仔细看。

**Comment by flyfish30** [comment]
是这样的，我一开始觉得是个错，可是这样应该不能通过编译，再检查了下，发现不是错误，只要变量名更换下就可以了。也就两分钟左右的时间间隔吧。
