### ISSUE TITLE
Meta issue

### ISSUE THREAD

**Issue by izgzhen** [ThoughtWorksInc/DeepDarkFantasy#188]
This is a meta issue about issues .... where I suggest:

- **Tag issues** according to their priority (urgent, medium, just-a-thought, etc.) and areas (optimization, tests, features...)
- Provide some introductory **write-ups** about the project (even if we can't maintain it well for now). http://marisa.moe/2017/DLPL/ is good, more is better, and a **roadmap** of implementations for interested folks would be nice

cc @MarisaKirisame

**Comment by MarisaKirisame** [comment]
Got it.

**Comment by MarisaKirisame** [comment]
For introductory writeup, preparing for talk on DDF right now. Will take some time.

**Comment by izgzhen** [comment]
I saw the tags, thanks a lot!

**Comment by MarisaKirisame** [comment]
Thx. If you got anymore problem I will work on them. I will be doing roadmap.
