### ISSUE TITLE
a question about how to use issue

### ISSUE THREAD

**Issue by timzaak** [ThoughtWorksInc/DeepDarkFantasy#98]
这个项目貌似每开发一个的feature，都会创建一个issue来做跟踪。然后在创建一次提交表明解决了哪个issue，然后关闭该issue。
是这个流程么？
为什么？
This project seems to create an issue before developing a feature, and then combine a commit with the issue and close issue.
Is it a personal habit or anything else?

**Comment by MarisaKirisame** [comment]
我当备忘录用了。。。

**Comment by MarisaKirisame** [comment]
不过还是可以当普通的啥啥啥用的，有啥都可以当issue提
还有问题吗？没有我关了

**Comment by MarisaKirisame** [comment]
Please reopen/open another issue if you have further question.

**Comment by timzaak** [comment]
哦哦，懂了。 
我以为ThoughtWorks 是这么个流程呢。。 把git log 写到issue里面，方便后续讨论。是我多想了，😀
